import React from 'react'
import Script from 'next/script'

const about = () => {
  return (
    <div>
      <div>About Page</div>
      <Script>
        {`alert("Welcome to Next App About Page")`}
      </Script>
    </div>
  )
}

export default about

export const metadata = {
  title: "About - Next App",
  description: "Generated by create next app",
};