"use client";
import React from 'react'
import Script from 'next/script'

const contact = () => {
  return (
    <div>
      <div>Contact Page</div>
      {/* <Script>
        {`alert("Welcome to Next App Contact Page")`}
      </Script> */}
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact - Next App",
  description: "Generated by create next app",
};