import { Inter } from "next/font/google";
// import "../globa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Home Page - Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
      <div className={inter.className}>
        <div>Admin Navbar</div>
        {children}
        <div>Admin Footer</div>
      </div>
  );
}